[connections.mysql]
dialect = "mysql"
driver = "pymysql"
host="localhost"
port=3306
database="vmstark_db"
username="root"
password="vmstark10!"


[passwords]
# Follow the rule: username = "password"
Buba = "123"
Dorel = "123"
